import { PowerBITheme, ThemePreset } from './types';

export const DEFAULT_THEME: PowerBITheme = {
  name: 'Custom Theme',
  dataColors: [
    '#118DFF',
    '#12239E',
    '#E66C37',
    '#6B007B',
    '#E044A7',
    '#744EC2',
    '#D9B300',
    '#D64550',
  ],
  background: '#FFFFFF',
  foreground: '#000000',
  tableAccent: '#118DFF',
  good: '#00B050',
  neutral: '#FFC000',
  bad: '#FF0000',
  maximum: '#118DFF',
  center: '#FFC000',
  minimum: '#DEEFFF',
  null: '#FF7F48',
};

export const PRESET_THEMES: ThemePreset[] = [
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    description: 'Professional blue palette for business reports',
    tags: ['Business', 'Professional'],
    category: 'business',
    theme: {
      name: 'Corporate Blue',
      dataColors: [
        '#0078D4',
        '#005A9E',
        '#50E6FF',
        '#008272',
        '#00B294',
        '#B4009E',
        '#5C2D91',
        '#00188F',
      ],
      background: '#FFFFFF',
      foreground: '#323130',
      tableAccent: '#0078D4',
      good: '#107C10',
      neutral: '#FFB900',
      bad: '#D13438',
      maximum: '#0078D4',
      center: '#FFB900',
      minimum: '#DEECF9',
      null: '#8A8886',
    },
  },
  {
    id: 'sunset-warm',
    name: 'Sunset Warm',
    description: 'Warm, energetic colors inspired by sunset',
    tags: ['Creative', 'Warm'],
    category: 'creative',
    theme: {
      name: 'Sunset Warm',
      dataColors: [
        '#FF6B35',
        '#F7931E',
        '#FDC830',
        '#E63946',
        '#FF8C42',
        '#D62828',
        '#F77F00',
        '#FCBF49',
      ],
      background: '#FFFCF7',
      foreground: '#2D1B00',
      tableAccent: '#FF6B35',
      good: '#52B788',
      neutral: '#F7931E',
      bad: '#E63946',
      maximum: '#E63946',
      center: '#F7931E',
      minimum: '#FEF0E6',
      null: '#A9A9A9',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    description: 'Natural, calming green tones',
    tags: ['Nature', 'Sustainability'],
    category: 'nature',
    theme: {
      name: 'Forest Green',
      dataColors: [
        '#2D6A4F',
        '#40916C',
        '#52B788',
        '#74C69D',
        '#95D5B2',
        '#1B4332',
        '#081C15',
        '#B7E4C7',
      ],
      background: '#F8FFF8',
      foreground: '#081C15',
      tableAccent: '#2D6A4F',
      good: '#40916C',
      neutral: '#F7B801',
      bad: '#D62828',
      maximum: '#081C15',
      center: '#52B788',
      minimum: '#D8F3DC',
      null: '#95D5B2',
    },
  },
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    description: 'Deep blues and teals for data depth',
    tags: ['Cool', 'Professional'],
    category: 'business',
    theme: {
      name: 'Ocean Depths',
      dataColors: [
        '#023E8A',
        '#0077B6',
        '#0096C7',
        '#00B4D8',
        '#48CAE4',
        '#012A4A',
        '#013A63',
        '#90E0EF',
      ],
      background: '#F7FBFF',
      foreground: '#012A4A',
      tableAccent: '#0077B6',
      good: '#06D6A0',
      neutral: '#FFD60A',
      bad: '#EF476F',
      maximum: '#012A4A',
      center: '#00B4D8',
      minimum: '#CAF0F8',
      null: '#ADB5BD',
    },
  },
  {
    id: 'modern-purple',
    name: 'Modern Purple',
    description: 'Contemporary purple palette with contrast',
    tags: ['Modern', 'Creative'],
    category: 'creative',
    theme: {
      name: 'Modern Purple',
      dataColors: [
        '#6A4C93',
        '#8B5FBF',
        '#A073D9',
        '#B388EB',
        '#C49BFF',
        '#512B81',
        '#3A1A6C',
        '#D4ADFC',
      ],
      background: '#FCFAFF',
      foreground: '#2B1B4A',
      tableAccent: '#6A4C93',
      good: '#06D6A0',
      neutral: '#FFD166',
      bad: '#EF476F',
      maximum: '#3A1A6C',
      center: '#8B5FBF',
      minimum: '#F2E7FE',
      null: '#B4A5C0',
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Elegant grayscale for minimalist reports',
    tags: ['Minimal', 'Elegant'],
    category: 'minimal',
    theme: {
      name: 'Monochrome',
      dataColors: [
        '#212529',
        '#495057',
        '#6C757D',
        '#ADB5BD',
        '#CED4DA',
        '#000000',
        '#343A40',
        '#E9ECEF',
      ],
      background: '#FFFFFF',
      foreground: '#212529',
      tableAccent: '#495057',
      good: '#28A745',
      neutral: '#FFC107',
      bad: '#DC3545',
      maximum: '#000000',
      center: '#6C757D',
      minimum: '#F8F9FA',
      null: '#ADB5BD',
    },
  },
  {
    id: 'vibrant-energy',
    name: 'Vibrant Energy',
    description: 'Bold, high-contrast colors for impact',
    tags: ['Bold', 'Energetic'],
    category: 'bold',
    theme: {
      name: 'Vibrant Energy',
      dataColors: [
        '#FF006E',
        '#FB5607',
        '#FFBE0B',
        '#8338EC',
        '#3A86FF',
        '#C1121F',
        '#FF4800',
        '#06FFA5',
      ],
      background: '#FFFFFF',
      foreground: '#000814',
      tableAccent: '#FF006E',
      good: '#06FFA5',
      neutral: '#FFBE0B',
      bad: '#C1121F',
      maximum: '#8338EC',
      center: '#FB5607',
      minimum: '#FFE5EC',
      null: '#8D99AE',
    },
  },
  {
    id: 'earth-tones',
    name: 'Earth Tones',
    description: 'Warm, grounded browns and oranges',
    tags: ['Warm', 'Natural'],
    category: 'nature',
    theme: {
      name: 'Earth Tones',
      dataColors: [
        '#8B4513',
        '#A0522D',
        '#CD853F',
        '#DEB887',
        '#D2691E',
        '#6B3410',
        '#F4A460',
        '#FFDAB9',
      ],
      background: '#FFF8F0',
      foreground: '#3E2723',
      tableAccent: '#8B4513',
      good: '#689F38',
      neutral: '#FFA726',
      bad: '#D32F2F',
      maximum: '#3E2723',
      center: '#CD853F',
      minimum: '#FFECD2',
      null: '#BCAAA4',
    },
  },
];
